import type { Metadata } from "next";
import { Barlow, Fraunces } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
  weight: ["600", "900"],
});

const fraunces = Fraunces({
  weight: ["700", "900"],
});

export const metadata: Metadata = {
  title: "Sunnyside agency landing page main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${barlow.className} ${fraunces.className}`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
